(defvar glad-json "{\"name\": \"Mikhail Tal\", \"winPercent\": 85.2}")
(defvar good-json "{\"name\": \"Nooby McNooberson\", \"winPercent\": null}")
(defvar dead-json "{\"name\": \"Never McWonAGame\", \"winPercent\": 0}")
(defvar bad-json "{\"name\": \"Nooby McNooberson\", 'winPercent': 33.3}")
(defvar rad-json "{\"fiz\": \"Nooby McNooberson\", \"baz\": null}")
(defvar sad-json "{\"fiz\": \"Nooby McNooberson\", \"baz\": false}")
